spring:
  application:
    name: zuul-service

server:
  port: 8000

zuul:
  routes:
    first-service:
      path: /first-service/**
      url: http://127.0.0.1:8082
    second-service:
      path: /second-service/**
      url: http://127.0.0.1:8081

