spring:
  application:
    name: discoveryservice

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false # eureka 서버에 등록할지 t/f
    fetch-registry: false # 레지스트리에서 server 정보를 캐싱할 지 t/f (30초마다 레지스트리에 서버정보 저장)
