server:
  port: 8000

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud GateWay GlobalFilter
            preLogger: true
            postLogger: true
      routes:
        - id: first-service
          #uri: http://127.0.0.1:8081/
          uri: lb://FIRST-SERVICE
          predicates:
            - Path=/first-service/**
          filters:
#              - AddRequestHeader=first-request, first-requests-header2
#              - AddResponseHeader=first-response, first-response-header2
            - name: CustomFilter
        - id: second-service
          #uri: http://127.0.0.1:8082/
          uri: lb://SECOND-SERVICE
          predicates:
            - Path=/second-service/**
          filters:
#              - AddRequestHeader=second-request, second-requests-header2
#              - AddResponseHeader=second-response, second-response-header2
            - name: CustomFilter
            - name: LoggingFilter
              args:
                baseMessage: Hi, there.
                preLogger: true
                postLogger: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      efaultZone: http://127.0.0.1:8761/eureka
#logging:
#  level:
#    root: debug