server:
  port: 8000

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud GateWay GlobalFilter
            preLogger: true
            postLogger: true
      routes:
        - id: first-service
          uri: http://localhost:8081/
          predicates:
            - Path=/first-service/**
          filters:
#              - AddRequestHeader=first-request, first-requests-header2
#              - AddResponseHeader=first-response, first-response-header2
            - CustomFilter
        - id: second-service
          uri: http://localhost:8082/
          predicates:
            - Path=/second-service/**
          filters:
#              - AddRequestHeader=second-request, second-requests-header2
#              - AddResponseHeader=second-response, second-response-header2
            - CustomFilter
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      efaultZone: http://localhost:8761/eureka
#logging:
#  level:
#    root: debug